"""Added Cascade Features

Revision ID: 2ae3b43d7368
Revises: a847f2d6080a
Create Date: 2023-08-19 14:38:15.985855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae3b43d7368'
down_revision = 'a847f2d6080a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
